data:
  02tahoe:
    audio: "POLICE"
    handling: "vsn02tahoeS"
  09charger:
    audio: "npolchar"
    handling: "vsn08chargerS"
  11cvpi:
    audio: "cvpiv8"
    handling: "11CVPI"
  13fpiu:
    audio: "ecoboostv6"
    handling: "13FPIU"
  14charger:
    audio: "npolchar"
    handling: "14CHARGER"
  14tahoe:
    audio: "granger"
    handling: "14TAHOE"
  16fpiu:
    audio: "ecoboostv6"
    handling: "18FPIS"
  18charger:
    audio: "npolchar"
    handling: "18CHARGER"
  18f150:
    audio: "aq02coyotef150"
    handling: "18F150"
  18f250:
    audio: "aq02coyotef150"
    handling: "18F250"
  18fpis:
    audio: "ecoboostv6"
    handling: "18FPIS"
  18tahoe:
    audio: "fbi2"
    handling: "18TAHOE"
  20fpiu:
    audio: "ecoboostv6"
    handling: "20FPIU"
  20ram:
    audio: "fbi2"
    handling: "20RAM"

vehicles:
  vsn11cvpi:
    data: "11cvpi" # link to data
    code: "bcrpd#" # auto increment
  vsn11cvpiS:
    data: "11cvpi" # link to data
    code: "bcrpds#" # auto increment

  vsn13fpiu:
    data: "13fpiu" # link to data
    code: "bcrpd#" # auto increment
  vsn13fpiuS:
    data: "13fpiu" # link to data
    code: "bcrpds#" # auto increment

  vsn13taurus:
    data: "18fpis" # link to data
    code: "bcrpd#" # auto increment
  vsn13taurusS:
    data: "18fpis" # link to data
    code: "bcrpds#" # auto increment

  vsn14charger:
    data: "14charger" # link to data
    code: "bcrpd#" # auto increment
  vsn14chargerS:
    data: "14charger" # link to data
    code: "bcrpds#" # auto increment

  vsn14tahoe:
    data: "14tahoe" # link to data
    code: "bcrpd#" # auto increment
  vsn14tahoeS:
    data: "14tahoe" # link to data
    code: "bcrpds#" # auto increment

  vsn16fpiu:
    data: "16fpiu" # link to data
    code: "bcrpd#" # auto increment
  vsn16fpiuS:
    data: "16fpiu" # link to data
    code: "bcrpds#" # auto increment
  
  vsn18charger:
    data: "18charger" # link to data
    code: "bcrpd#" # auto increment
  vsn18chargerS:
    data: "18charger" # link to data
    code: "bcrpds#" # auto increment

  vsn18f150:
    data: "18f150" # link to data
    code: "bcrpd#" # auto increment
  vsn18f150S:
    data: "18f150" # link to data
    code: "bcrpds#" # auto increment

  vsn18tahoe:
    data: "18tahoe" # link to data
    code: "bcrpd#" # auto increment
  vsn18tahoeS:
    data: "18tahoe" # link to data
    code: "bcrpds#" # auto increment

  vsn20fpiu:
    data: "20fpiu" # link to data
    code: "bcrpd#" # auto increment
  vsn20fpiuS:
    data: "20fpiu" # link to data
    code: "bcrpds#" # auto increment

  vsn08chargerS:
    data: "09charger" # link to data
    code: "bcrpds#" # auto increment
  vsn02tahoeS:
    data: "02tahoe" # link to data
    code: "bcrpds#" # auto increment